- name: Ensure the cert manager namespace exists
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: cert-manager
    state: present

- name: Add the jetstack helm chart repo
  community.kubernetes.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Add cert manager crds
  community.kubernetes.k8s:
    definition: "{{ lookup('url', 'https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.crds.yaml', split_lines=False) }}"
    state: present

- name: Install cert manager
  community.kubernetes.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: v0.15.1
    release_namespace: cert-manager
    values:
      ingressShim:
        defaultIssuerName: letsencrypt-prod
        defaultIssuerKind: ClusterIssuer

- name: Add cluster issuer
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'cluster-issuer.yml.j2') }}"
    namespace: cert-manager
    state: present
